### ISSUE TITLE
ui: family-journeys shared location popup date has incorrect century

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/sites-of-shame#222]
The dates in the "n members of the X family were here" popups at shared locations shows dates that are in the wrong century (e.g., "2043" instead of "1943")

**Comment by GeoffFroh** [comment]
Fixed in a0c4b9344ac5962caaf8e9459e8a414be8bc2ebb

**Comment by gjost** [comment]
I can't seem to get the changes to appear on the stage site (https://sosstage.densho.org/).  Things I've tried so far:
On `packrat`:
- Ran `git fetch` and checked out the `222-hotfix-familyjourneydates` branch.
- Ran `make build-stage` which runs `yarnpkg staging`.
- Ran `make push-stage` which rsyncs contents of `build/` to `kiki`.
- Saw no change on `sosstage...`.
- Realized mistake and edited 'Makefile` to rsync to `gordo` instead of `kiki`.
- Ran `make push-stage` again.  Still no change.
- `rm -Rf build/*`, `make build-stage`, and `make push-stage` again.  Still no change.

**Comment by gjost** [comment]
The `make build-stage` step complains of a missing `paramiko` which is a Python SSH library. I'm not sure why that should be the case

**Comment by gjost** [comment]
Got everything worked out.  The app was actually getting data from `densho-sites-of-shame-data`.
